name: cvt2bids
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - setuptools
  - numpy
  - ipykernel
  - python=3
  - dcm2niix
  - dcm2bids
  - pandas
  - pydicom
  - pip
  - pip:
      - nibabel
      - setuptools-scm
      - python-dotenv
      - pydicom
